version: "3"
services:
  db:
    image: couchbase:community-7.2.4
    container_name: couchbase-server
    networks:
      - internal-default
    hostname: library-service-db
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210

  db-init:
    container_name: couchbase-server-init
    build:
      dockerfile: ./.couchbase/Dockerfile
    networks:
      - internal-default
    hostname: library-service-db-init
    depends_on:
      - db
    restart: "no"
    entrypoint: [ "bash", "-c", "./wait-for-url.sh && ./configure-couchbase.sh"]

  library-service:
    depends_on:
      - db
    networks:
      - internal-default
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:  
      - BUCKET_PASSWORD=password
      - NODE_URL=couchbase://library-service-db

networks:
  internal-default:
    name: internal-default
    driver: bridge

volumes:
  library-service-db-vol: