spring:
    application:
        name: library-service

db:
    couchbase:
        node-list: ${NODE_URL}
        bucket-name: library
        bucket-username: default
        bucket-password: ${BUCKET_PASSWORD}